d3ledger/notary

- src/main/kotlin/notary/NotaryInitialization.kt
- src/main/resources/defaults.properties
Fix key loading path for Iroha.
Fix error handling with Result.
> fix iroha keys location

- deploy/iroha/deploy.sh
> run iroha container in detached mode (-d)

- deploy/ethereum/config/node0.toml
- deploy/ethereum/contract/notary.sol
- deploy/ethereum/genesis.json
Very basic smart contract implementation. Currently it's far from production level quality/functionality but can be useful for development.
How to use it:
1. Deploy ERC-20 token into parity (you can use https://gist.github.com/luckychess/0237fc2ca73a1a39d44f3b661156eaf4 for example)
2. Deploy this smart contract.
3. Transfer some tokens to address of this contract.
The only interesting method at the moment is ```withdrawTokens(address coin_address, uint256 amount, address to, bytes32 hash, uint8 v, bytes32 r, bytes32 s)``` (its interface will be probably simplified in the future). You have to pass address of ERC-20 token contract (see p. 1), amount of tokens you want to withdraw, your address you want withdraw to, keccak256 hash (of any string for now) and secp256k1 signature of hash (v, …
> Add simple smart contract implementation

- deploy/waves/Dockerfile
- deploy/waves/deploy.sh
- deploy/waves/genesis.conf
- deploy/waves/settings.conf
Waves private network deploy
References:
https://docs.wavesplatform.com/technical-details/creating-a-private-waves-blockchain-network.html
https://documenter.getpostman.com/view/2733299/waves-full-node/RVnWiKZJ
> Deploy waves

- deploy/ethereum/config/node0.toml
- deploy/ethereum/config/node1.toml
- deploy/ethereum/deploy.sh
- deploy/ethereum/entrypoint.sh
Fixes keys path 
Removes UI, since it is deprecated
> Remove UI, fix paths

- build.gradle
- src/test/kotlin/vendor/KtorUsageTest.kt
Fix settings for JUnit 5. Now tests are going to pass.
> Fix missing tests with junit 5

- deploy/iroha/deploy.sh
This iroha tag is the latest built, with right schema
> Add latest iroha image

- deploy/iroha/deploy.sh
Pull actual iroha image before running it
> Actual iroha docker image

- build.gradle
Added task to build Ethereum smart contracts and java classes
> Gradle build contracts

- src/main/kotlin/notary/NotaryInitialization.kt
- src/main/kotlin/notary/main.kt
- src/main/kotlin/sidechain/iroha/IrohaInitialization.kt
- src/main/kotlin/withdrawalservice/main.kt
- src/test/integration/IntegrationTest.kt
- src/test/kotlin/sidechain/iroha/consumer/IrohaKeyLoaderTest.kt
> Fix typo in IrohaInitialization

- src/main/kotlin/endpoint/RefundServerEndpoint.kt
- src/main/kotlin/sidechain/iroha/IrohaChainListener.kt
fix rxjava
Previously Observable was on schedule, fix it.
> add Iroha output to registration

- build.gradle
- deploy/iroha/deploy.sh
- src/main/kotlin/registration/EthFreeWalletsProvider.kt
- src/main/kotlin/registration/RegistrationServiceInitialization.kt
- src/test/integration/EthFreeWalletsProviderTest.kt
add relay provider that reads free relays from master notary account and return first one
> add relay provider

- build.gradle
- src/main/kotlin/registration/main.kt
Add gradle task to run registration
> add runRegistration at gradle

- src/main/kotlin/main/ConfigKeys.kt
- src/main/kotlin/registration/relay/RelayRegistration.kt
- src/main/kotlin/registration/relay/main.kt
- src/main/resources/relay_registration_defaults.properties
Add relay smart contract deployment.
> add deployment of relay smart contracts

- build.gradle
- src/main/kotlin/registration/relay/RelayRegistration.kt
- src/main/kotlin/registration/relay/main.kt
add relayRegistration at gradle
> add relayRegistration at gradle

- deploy/iroha/genesis.block
Iroha changes Block schema, and `deploy.sh` did not work
This pr fixes it
> Update iroha genesis block

- src/test/integration/IntegrationTest.kt
- src/test/kotlin/registration/RegistrationTest.kt
> add deposit ERC20 token

- build.gradle
> Fix gradle build

- src/main/kotlin/notary/EthWalletsProviderIrohaImpl.kt
- src/main/kotlin/notary/EthWalletsProviderPostgresImpl.kt
- src/main/kotlin/notary/NotaryInitialization.kt
- src/main/kotlin/sideChain/iroha/util/ModelUtil.kt
- src/main/kotlin/sidechain/iroha/consumer/IrohaNetworkImpl.kt
- src/test/kotlin/registration/EthWalletsProviderIrohaTest.kt
Store wallets in Iroha instead of Postgres
> Add iroha wallet storage

- build.gradle
- src/main/kotlin/notary/main.kt
- src/main/kotlin/registration/main.kt
- src/main/kotlin/registration/relay/main.kt
- src/main/kotlin/withdrawalservice/WithdrawalServiceInitialization.kt
- src/main/kotlin/withdrawalservice/main.kt
Add gradle tasks for executables
> add gradle tasks for executables

- src/main/kotlin/notary/EthWalletsProviderIrohaImpl.kt
- src/main/kotlin/notary/NotaryInitialization.kt
- src/main/kotlin/sideChain/iroha/util/ModelUtil.kt
- src/main/kotlin/sidechain/iroha/IrohaChainListener.kt
- src/main/kotlin/sidechain/iroha/consumer/IrohaNetworkImpl.kt
- src/main/kotlin/withdrawalservice/WithdrawalServiceInitialization.kt
- src/test/kotlin/notary/NotaryTest.kt
- src/test/kotlin/sidechain/iroha/IrohaBlockStreamingTest.kt
Fix iroha configs, previously default parameters with `localhost` were used that makes impossible to deploy notary.
> fix iroha configs

- deploy/docker-compose-full.yml
- deploy/grpcwebproxy/Dockerfile
Signed-off-by: Artyom Bakhtin <a@bakhtin.net>
> grpcwebproxy docker-compose service

- deploy/docker-compose-full.yml
> Fix for docker-compose-full.yml

- src/main/kotlin/registration/EthFreeWalletsProvider.kt
- src/main/kotlin/sidechain/iroha/util/RequestHelper.kt
fix bug with empty relays in Iroha
> fix empty relay provider

- src/test/integration/EthFreeWalletsProviderTest.kt
Fix EthFreeWalletsProviderTest with correct account detail creator.
> Fix EthFreeWalletsProviderTest

- src/main/kotlin/notary/NotaryImpl.kt
- src/main/kotlin/sidechain/ChainEvent.kt
- src/main/kotlin/sidechain/eth/EthChainHandler.kt
- src/test/kotlin/notary/NotaryTest.kt
Add 'from' Ethereum address to tx transfer in Iroha when deposit arises.
> add `from` to iroha tx from eth deposit

- build.gradle
- src/main/kotlin/withdrawalservice/main.kt
> add JaCoCo coverage

- deploy/db/sql/init/populate.sql
- src/main/kotlin/sideChain/iroha/util/ModelUtil.kt
- src/main/kotlin/sidechain/eth/EthChainHandler.kt
- src/main/kotlin/sidechain/eth/util/DeployHelper.kt
- src/test/integration/ContractsTest.kt
- src/test/integration/IntegrationTest.kt
Deploy ERC20 to ropsten.
Add them to list.
> add list of supported eth tokens

- src/integration-test/kotlin/integration/ContractsTest.kt
> Add test to relay-to-relay withdrawal case

- src/main/kotlin/registration/relay/RelayRegistration.kt
Remove Iroha network layer away from RelayRegistration.
> rework RelayRegistration - move iroha network layer away

- build.gradle
- src/integration-test/kotlin/integration/VacuumIntegrationTest.kt
- src/main/kotlin/notary/EthWalletsProviderIrohaImpl.kt
- src/main/kotlin/sidechain/eth/util/DeployHelper.kt
- src/main/kotlin/vacuum/RelayVacuum.kt
- src/main/kotlin/vacuum/RelayVacuumConfig.kt
- src/main/kotlin/vacuum/main.kt
- src/main/resources/defaults.properties
- src/main/resources/defaults_deploy.properties
New functionality for moving assets from deployed relay contracts to master contract
> Relay tokens vacuumer

- src/integration-test/kotlin/integration/DepositIntegrationTest.kt
- src/integration-test/kotlin/integration/IntegrationTest.kt
- src/integration-test/kotlin/integration/WithdrawalIntegrationTest.kt
- src/main/kotlin/sideChain/iroha/util/ModelUtil.kt
Move deposit cases to separate file.
> Rework deposit case in integration tests

- deploy/iroha/genesis.block
- src/main/resources/defaults.properties
- src/main/resources/defaults_deploy.properties
Add vacuumer role with coherent permissions to Iroha genesis block.
> add vacuumer role

- src/main/kotlin/notary/Notary.kt
- src/main/kotlin/notary/NotaryImpl.kt
- src/main/kotlin/notary/NotaryInitialization.kt
- src/main/kotlin/sidechain/eth/EthChainHandler.kt
- src/test/kotlin/notary/NotaryTest.kt
Remove iroha listener from notary, since it is not needed there
> Remove iroha listener

- src/main/kotlin/config/Configs.kt
- src/main/kotlin/notary/NotaryConfig.kt
- src/main/resources/notary.properties
Add bitcoin config and run bitcoin testnet node
> Add bitcoin config

- src/integration-test/kotlin/integration/WithdrawalIntegrationTest.kt
- src/integration-test/kotlin/integration/helper/IntegrationHelperUtil.kt
- src/integration-test/resources/ethereum_password.properties
- src/integration-test/resources/notary.properties
- src/integration-test/resources/notary_deploy.properties
- src/integration-test/resources/test.properties
- src/integration-test/resources/test_deploy.properties
- src/main/kotlin/notary/endpoint/RefundServerEndpoint.kt
Fix and rework WithdrawalIntegrationTest.
Now it is working with ganache, pass time reduced.
Next step is to include it to CI pipeline.
> WithdrawalIntegrationTest fix

- build.gradle
- src/main/kotlin/config/Configs.kt
- src/main/kotlin/notary/NotaryConfig.kt
- src/main/kotlin/registration/relay/RelayRegistrationConfig.kt
- src/main/kotlin/withdrawalservice/WithdrawalServiceConfig.kt
- src/main/kotlin/withdrawalservice/WithdrawalServiceInitialization.kt
- src/main/resources/defaults.properties
- src/main/resources/defaults_deploy.properties
- src/main/resources/notary.properties
- src/main/resources/notary_deploy.properties
- src/main/resources/relay_registration.properties
- src/main/resources/relay_registration_deploy.properties
- src/main/resources/vacuum.properties
- src/main/resources/vacuum_deploy.properties
- src/main/resources/withdrawal.properties
- src/main/resources/withdrawal_deploy.properties
- src/test/kotlin/config/TestConfig.kt
- src/test/kotlin/notary/NotaryInitializationTest.kt
- src/test/resources/test.properties
- src/test/resources/test_deploy.properties
Refactor configs a bit:
- Remove unused database configs
- fix some configs
- rework profiles in gradle to support not only defaults
> Configs again

- src/integration-test/kotlin/integration/EthRelayProviderIrohaTest.kt
> fix EthRelayProviderTest

- src/integration-test/kotlin/integration/ContractsTest.kt
Just several unit tests. To check them run ganache-cli first (with docker-compose dev or manually).
> Add smart contract tests for vacuum

- build.gradle
- src/integration-test/kotlin/integration/IrohaBatchTest.kt
- src/integration-test/kotlin/integration/WithdrawalIntegrationTest.kt
- src/main/kotlin/notary/NotaryInitialization.kt
- src/main/kotlin/notary/endpoint/eth/EthRefundStrategyImpl.kt
- src/main/kotlin/sidechain/eth/util/TokenListConverter.kt
- src/main/kotlin/withdrawalservice/WithdrawalServiceImpl.kt
Also bug in EthRefundStrategyImpl was fixed.
> Request proofs from all known notaries

- deploy/iroha/genesis.block
Add permissions related to quorum to tester role.
Pros: Slava is happy.
Cons: No.
> add perms with quorum for tester

- src/main/resources/eth/notary_mainnet.properties
- src/main/resources/eth/registration_mainnet.properties
- src/main/resources/eth/relay_registration_mainnet.properties
- src/main/resources/eth/vacuum_mainnet.properties
- src/main/resources/eth/withdrawal_mainnet.properties
> Fix wrong param names in mainnet configs

- deploy-relay.dockerfile
- notary.dockerfile
- registration.dockerfile
- withdrawal.dockerfile
> replace gradle docker with official one

- Jenkinsfile
- deploy/docker-compose.ci.yml
- Collect logs from containers upon test completion. Compress and store as build artifact
- Publish test results on Jenkins CI using `junit` plugin
- Move builds to a separate AWS EC2 agent. An instance is deployed for each build and shut down on completion
> Build artifacts (logs, test results)

- src/main/kotlin/sidechain/eth/consumer/EthConsumer.kt
Check for the exact topic name and start a vacuum
> check topic

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Upgrades gradle wrapper version
> Upgrade gradlew version

- btc-pregeneration/src/main/kotlin/pregeneration/btc/config/BtcPreGenerationAppConfiguration.kt
- btc-pregeneration/src/main/kotlin/pregeneration/btc/main.kt
- btc-registration/src/main/kotlin/registration/btc/main.kt
- btc/src/main/kotlin/provider/btc/BtcPublicKeyProvider.kt
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcPreGenIntegrationTest.kt
Spring configuration refactor.
> Fixed Spring configuration

- btc-deposit/src/main/kotlin/notary/btc/config/BtcNotaryAppConfiguration.kt
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcNotaryIntegrationTest.kt
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcPreGenIntegrationTest.kt
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcRegistrationIntegrationTest.kt
- notary-integration-test/src/main/kotlin/integration/helper/IntegrationHelperUtil.kt
Bitcoin deposit service became very compilcated. It's not simple anymore as it was before. New integration tests were written to keep service in consistent state.
> More BTC notary integration tests

- .gitignore
- btc-withdrawal/build.gradle
- btc-withdrawal/src/main/kotlin/withdrawal/btc/BtcWithdrawalInitialization.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/config/BtcWithdrawalAppConfiguration.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/config/BtcWithdrawalConfig.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/main.kt
- btc-withdrawal/src/main/resources/application.yml
- btc-withdrawal/src/main/resources/log4j.properties
- configs/btc/withdrawal_local.properties
- configs/btc/withdrawal_testnet.properties
- deploy/iroha/genesis.block
- notary-integration-test/build.gradle
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcNotaryIntegrationTest.kt
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcWithdrawalIntegrationTest.kt
- notary-integration-test/src/main/kotlin/integration/helper/AccountHelper.kt
- notary-integration-test/src/main/kotlin/integration/helper/ConfigHelper.kt
- notary-integration-test/src/main/kotlin/integration/helper/IntegrationHelperUtil.kt
- settings.gradle
- src/main/kotlin/sidechain/iroha/util/RequestHelper.kt
Skeleton for bitcoin withdrawal service:
1. New gradle project `btc-withdrawal`
2. New gradle task `./gradlew runBtcWithdrawal`
3. New account `btc_withdrawal_service` in genesis block that is used to execute transfers and listen to newly created transfers
4. New dummy integration test with no logic in it
> Bitcoin withdrawal skeleton

- btc-deposit/src/main/kotlin/notary/btc/listener/BitcoinTransactionListener.kt
- btc-registration/src/main/kotlin/registration/btc/BtcRegistrationStrategyImpl.kt
- btc-withdrawal/src/main/kotlin/withdrawal/transaction/TransactionHelper.kt
- btc/src/main/kotlin/provider/btc/BtcPublicKeyProvider.kt
- btc/src/main/kotlin/provider/btc/address/BtcAddress.kt
- btc/src/main/kotlin/provider/btc/address/BtcAddressesProvider.kt
- btc/src/main/kotlin/provider/btc/address/BtcRegisteredAddressesProvider.kt
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcPreGenIntegrationTest.kt
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcRegistrationIntegrationTest.kt
- notary-integration-test/src/main/kotlin/integration/helper/IntegrationHelperUtil.kt
- src/main/kotlin/registration/IrohaAccountCreator.kt
Now we store all public keys that were used in multisignature address creation process. Keys are stored in JSON.
> Storing public keys for multisignature addresses

- btc-registration/src/main/kotlin/registration/btc/BtcRegistrationStrategyImpl.kt
- btc-registration/src/main/kotlin/registration/btc/config/BtcRegistrationAppConfiguration.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/BtcWhiteListProvider.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/BtcWithdrawalInitialization.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/config/BtcWithdrawalAppConfiguration.kt
- btc/src/main/kotlin/provider/btc/account/IrohaBtcAccountCreator.kt
- deploy/iroha/genesis.block
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcRegistrationIntegrationTest.kt
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcWithdrawalIntegrationTest.kt
- notary-integration-test/src/main/kotlin/integration/helper/IntegrationHelperUtil.kt
- src/main/kotlin/notary/endpoint/eth/EthRefundStrategyImpl.kt
- src/main/kotlin/notary/endpoint/eth/EthWhiteListProvider.kt
- src/main/kotlin/provider/WhiteListProvider.kt
- src/main/kotlin/registration/IrohaAccountCreator.kt
- src/main/kotlin/registration/IrohaEthAccountCreator.kt
- src/main/kotlin/registration/eth/EthRegistrationStrategyImpl.kt
Bitcoin whitelist implementation. Works the same way as in Ethereum services. A whitelist is stored in client account details and checked every time withdrawal event happens.
> Bitcoin white list

- btc-deposit/src/main/kotlin/notary/btc/BtcNotaryInitialization.kt
- btc-deposit/src/main/kotlin/notary/btc/listener/BitcoinTransactionListener.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/BtcWithdrawalInitialization.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/TimedTx.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/config/BtcWithdrawalAppConfiguration.kt
- btc-withdrawal/src/main/kotlin/withdrawal/transaction/SignCollector.kt
- btc-withdrawal/src/main/kotlin/withdrawal/transaction/TransactionHelper.kt
- btc-withdrawal/src/main/kotlin/withdrawal/transaction/TransactionSigner.kt
- btc/src/main/kotlin/helper/address/BtcAddressHelper.kt
- btc/src/main/kotlin/provider/btc/BtcPublicKeyProvider.kt
- btc/src/main/kotlin/provider/btc/address/BtcAddress.kt
- deploy/iroha/genesis.block
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcNotaryIntegrationTest.kt
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcWithdrawalIntegrationTest.kt
- notary-integration-test/src/main/kotlin/integration/helper/AccountHelper.kt
- notary-integration-test/src/main/kotlin/integration/helper/IntegrationHelperUtil.kt
- src/main/kotlin/sidechain/iroha/IrohaVals.kt
- src/main/kotlin/util/StringExt.kt
- src/test/kotlin/util/StringExtTest.kt
Tx signing process. Consists of three consecutive steps:
1) Sign tx
2) Create an account for storing signatures
3) Collect signatures from all the nodes into that account details
> Bitcoin tx signing process

- Jenkinsfile
- btc-deposit/build.gradle
- btc-pregeneration/build.gradle
- btc-registration/build.gradle
- btc-withdrawal/build.gradle
- btc/build.gradle
- build.gradle
- d3testreport/build.gradle
- notary-integration-test/build.gradle
- settings.gradle
- test-longevity/build.gradle
1. Code coverage with JaCoCo and reports in Jenkins
How to use: `./gradlew codeCoverageReport`
2. Detailed JaCoCo reports now stores in artifacts (`jacoco.log.gz`)
3. Security analysis with Sonarqube: 
https://sonar.soramitsu.co.jp/dashboard?id=d3%3Anotary
4. Test documentation for Kotlin using dokka plugin (https://github.com/Kotlin/dokka)
> Feature: D3 Quality gate

- src/main/kotlin/registration/IrohaAccountCreator.kt
- src/test/java/registration/IrohaAccountCreatorTest.java
The registration process is divided into 3 transactions combined into one batch:
1) Create an account
2) Set certain details
3) Set whitelist
Now we can check if this batch failed. The first transaction may fail, but it's considered ok.
> Registration without account creation

- btc-withdrawal/src/main/kotlin/withdrawal/btc/handler/WithdrawalTransferEventHandler.kt
- btc/src/main/kotlin/helper/address/BtcAddressHelper.kt
Transfer address is checked before any Iroha interaction.
> Base58 address format check

- doc/api-client.md
> add client API

- src/main/kotlin/registration/IrohaAccountCreator.kt
Combine SetAccountDetail txs into one. There is no need to separate them.
> combine txs in accountCreation

- btc-withdrawal/build.gradle
- btc-withdrawal/src/main/kotlin/withdrawal/btc/send/SendBtc.kt
- configs/btc/withdrawal_local.properties
- configs/btc/withdrawal_testnet.properties
Now we can easily send BTC using task `sendBtc`. 
Usage: `./gradlew sendBtc -Paddress=your_address -Pamount=your_amount_in_sat`
> Transfer BTC gradle task

- deploy/docker-compose.yml
Introduced fixed iroha version, no surprises per each iroha push
> Set fixed iroha version

- build.gradle
Update kotlin to 1.3.10
Coroutines are released.
> update kotlin to 1.3.10

- grpc_healthcheck.kts
> fix comment in grpc script

- btc-withdrawal/src/main/kotlin/withdrawal/btc/BtcWithdrawalInitialization.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/provider/BtcChangeAddressProvider.kt
Change address must be added to a wallet explicitly to make it "watched"
> Change address is watched

- btc-deposit/src/main/kotlin/notary/btc/BtcNotaryInitialization.kt
- btc-deposit/src/main/kotlin/notary/btc/main.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/BtcWithdrawalInitialization.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/handler/WithdrawalTransferEventHandler.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/main.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/transaction/SignCollector.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/transaction/TransactionSigner.kt
- btc/src/main/kotlin/handler/btc/NewBtcClientRegistrationHandler.kt
- btc/src/main/kotlin/listener/btc/NewBtcClientRegistrationListener.kt
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcNotaryIntegrationTest.kt
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcWithdrawalIntegrationTest.kt
Registration and withdrawal services are well synchronized now. A newly registered address will be handled by withdrawal component.
> Bitcoin withdrawal-registration sync

- btc/src/main/kotlin/helper/network/BitcoinNetworkHelper.kt
- build.gradle
- grpc_healthcheck.kts
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcAddressGenerationIntegrationTest.kt
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcRegistrationIntegrationTest.kt
- notary-integration-test/src/integration-test/kotlin/integration/eth/WithdrawalPipelineIntegrationTest.kt
- notary-integration-test/src/integration-test/kotlin/integration/iroha/IrohaBatchTest.kt
- notary-integration-test/src/integration-test/kotlin/integration/iroha/IrohaBlockStreamingTest.kt
- notary-integration-test/src/main/kotlin/integration/helper/IntegrationHelperUtil.kt
- src/test/kotlin/registration/RegistrationTest.kt
- test-longevity/src/main/kotlin/longevity/LongevityTest.kt
Update coroutines to the latest version.
> update kotlin coroutines to 1.0.1

- btc-address-generation/src/main/kotlin/generation/btc/BtcAddressGenerationInitialization.kt
- btc-address-generation/src/main/kotlin/generation/btc/main.kt
- btc-address-generation/src/main/kotlin/generation/btc/trigger/AddressGenerationTrigger.kt
- btc-address-generation/src/main/kotlin/generation/btc/trigger/BtcAddressGenerationTriggerAppConfiguration.kt
- btc-deposit/src/main/kotlin/notary/btc/BtcNotaryInitialization.kt
- btc-deposit/src/main/kotlin/notary/btc/config/BtcNotaryAppConfiguration.kt
- btc-deposit/src/main/kotlin/notary/btc/main.kt
- btc-withdrawal/build.gradle
- btc-withdrawal/src/main/kotlin/withdrawal/btc/BtcWithdrawalInitialization.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/config/BtcWithdrawalAppConfiguration.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/handler/NewSignatureEventHandler.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/handler/WithdrawalTransferEventHandler.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/main.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/provider/BtcChangeAddressProvider.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/statistics/WithdrawalStatistics.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/transaction/UnsignedTransactions.kt
- btc/src/main/kotlin/monitoring/Monitoring.kt
- btc/src/main/kotlin/provider/btc/address/BtcAddress.kt
- btc/src/main/kotlin/provider/btc/address/BtcAddressesProvider.kt
- btc/src/main/kotlin/provider/btc/address/BtcRegisteredAddressesProvider.kt
- btc/src/main/kotlin/provider/btc/generation/BtcPublicKeyProvider.kt
- btc/src/main/kotlin/provider/btc/generation/BtcSessionProvider.kt
- btc/src/main/kotlin/provider/btc/wallet/WalletMonitoring.kt
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcAddressGenerationIntegrationTest.kt
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcNotaryIntegrationTest.kt
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcWithdrawalIntegrationTest.kt
- src/main/kotlin/util/StringExt.kt
Spring based JMX monitoring was added. You can get this information using jconsole or any other JMX client.
> Bitcoin monitoring

- btc-deposit/src/main/kotlin/notary/btc/BtcNotaryInitialization.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/BtcWithdrawalInitialization.kt
- btc/src/main/kotlin/helper/network/BitcoinNetworkHelper.kt
- configs/btc/notary_local.properties
- configs/btc/notary_testnet.properties
- configs/btc/withdrawal_local.properties
- configs/btc/withdrawal_testnet.properties
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcConfigHelper.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcIntegrationHelperUtil.kt
- src/main/kotlin/config/Configs.kt
- src/test/kotlin/config/BitcoinConfigTest.kt
In a current implementation, we can be connected to one full node only. But we may increase system stability by connecting to multiple full nodes.
> Multiple nodes

- btc-withdrawal/src/main/kotlin/withdrawal/btc/transaction/TransactionHelper.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcWithdrawalIntegrationTest.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcIntegrationHelperUtil.kt
A transaction is considered a 'dust' if its value is less than its fee. It's senseless to use these transactions as UTXO from an economic point of view.
> Handling dusty transactions

- btc-withdrawal/src/main/kotlin/withdrawal/btc/handler/WithdrawalTransferEventHandler.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/transaction/TransactionHelper.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcFullPipelineTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcWithdrawalIntegrationTest.kt
We cannot perform withdrawal if its value is too small. Now it's checked.
> Restrict small amount spending

- README.md
Bitcoin deploy notes were added
> Bitcoin deploy notes

- Jenkinsfile
Fixes automated push to nexus docker hub
> Separate shadow jar

- configs/eth/relay_registration_local.properties
- configs/eth/relay_registration_mainnet.properties
- configs/eth/relay_registration_testnet.properties
- deploy/iroha/genesis.block
- eth-registration/src/main/kotlin/registration/eth/relay/RelayRegistration.kt
- eth-registration/src/main/kotlin/registration/eth/relay/RelayRegistrationConfig.kt
- eth-registration/src/main/kotlin/registration/eth/relay/main.kt
- eth/src/main/kotlin/provider/eth/EthFreeRelayProvider.kt
- notary-eth-integration-test/src/main/kotlin/integration/helper/EthConfigHelper.kt
- notary-eth-integration-test/src/main/kotlin/integration/helper/EthIntegrationHelperUtil.kt
> add automatic relay deployment logic

- deploy/ethereum/tokens/testnet_tokens.json
Fix DGD ERC20 token precision.
> fix DGD precision (actual 9)

- eth-erc20-registration/build.gradle
- eth-registration/build.gradle
- eth-vacuum/build.gradle
- eth-withdrawal/build.gradle
- eth/build.gradle
Fixed working directory of eth services in order to locate configs correctly.
Probably there are simillar problem with bitcoin services. Bitcoin related fixes are going to be pushed by @dolgopolovwork
> Fixed working directory of eth services

- btc-address-generation/build.gradle
- btc-address-generation/src/main/kotlin/generation/btc/config/BtcAddressGenerationAppConfiguration.kt
- btc-address-generation/src/main/kotlin/generation/btc/init/BtcAddressGenerationInitialization.kt
- btc-address-generation/src/main/kotlin/generation/btc/trigger/BtcAddressGenerationTriggerAppConfiguration.kt
- btc-deposit/build.gradle
- btc-deposit/src/main/kotlin/notary/btc/init/BtcNotaryInitialization.kt
- btc-deposit/src/main/kotlin/notary/btc/main.kt
- btc-dw-bridge/build.gradle
- btc-registration/build.gradle
- btc-withdrawal/build.gradle
- btc-withdrawal/src/main/kotlin/withdrawal/btc/send/SendBtc.kt
- btc/build.gradle
- build.gradle
- notary-btc-integration-test/build.gradle
- test-longevity/build.gradle
Fixing bugs and crushes after migration to IPJ
> Bitcoin services stabilization after migration to IPJ

- Jenkinsfile
- btc-address-generation/build.gradle
- btc-dw-bridge/build.gradle
- btc-registration/build.gradle
- build_and_push_nexus.sh
- deploy/docker-compose-base.yml
- deploy/docker-compose-full.yml
- deploy/docker-compose-single.yml
- docker/btc-address-generation.dockerfile
- docker/btc-dw-bridge.dockerfile
- docker/btc-registration.dockerfile
- docker/entrypoint.sh
- docker/etg-registration.dockerfile
- docker/eth-withdrawal.dockerfile
- docker/notary.dockerfile
Updated docker files, added bitcoin services
> Relevant docker files

- deploy/docker-compose-base.yml
- deploy/docker-compose.dev.yml
- deploy/docker-compose.yml
> Fix wait for iroha bug

- deploy/docker-compose-full.yml
- deploy/docker-compose-single.yml
docker-compose.
Move btc services from docker-compose-singel to docker-compose-full.
> Fix btc docker. Move dw and address geneartion from single to full

- Jenkinsfile
> Added btc build commands to Jenkinsfile

- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcAddressGenerationIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcFullPipelineTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcNotaryIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcWithdrawalIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcAddressGenerationTestEnvironment.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcWithdrawalTestEnvironment.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcIntegrationHelperUtil.kt
Fixing build. Probably too many blocks were generated during the initial phase.
> Fixing build

- configs/btc/withdrawal_testnet.properties
- eth/src/main/java/contract/BasicCoin.java
- eth/src/main/java/contract/Master.java
- eth/src/main/java/contract/Relay.java
- eth/src/main/java/contract/RelayRegistry.java
- eth/src/main/kotlin/deploy/sendEther.kt
- eth/src/main/kotlin/sidechain/eth/util/Crypto.kt
- notary-eth-integration-test/src/main/kotlin/integration/helper/ContractTestHelper.kt
Backward merge - to be able merge without conflicts in future
> Release/v0.2.1 alpha - merge to develop

- d3testreport/build.gradle
- d3testreport/src/main/java/MainHtml.java
- d3testreport/src/main/java/MainJson.java
- d3testreport/src/main/java/d3/report/enums/TestFolder.java
- d3testreport/src/main/java/d3/report/model/Summary.java
- d3testreport/src/main/java/d3/report/service/TestReportService.java
- d3testreport/src/main/resources/report.html
- d3testreport/src/test/java/d3/report/service/TestReportServiceTest.java
Integration test folders were changed. This causes test report generation failures. Now it's fixed and guarded by a simple test.
> Fixed report generator

- btc-registration/src/main/kotlin/registration/btc/strategy/BtcRegistrationStrategyImpl.kt
- doc/api-client.md
- eth-registration/src/main/kotlin/registration/eth/EthRegistrationStrategyImpl.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcRegistrationIntegrationTest.kt
- notary-commons/src/main/kotlin/registration/RegistrationServiceEndpoint.kt
- notary-commons/src/main/kotlin/registration/RegistrationStrategy.kt
- notary-registration/src/main/kotlin/registration/NotaryRegistrationStrategy.kt
Add API endpoint for registration service get relays number.
Implemented for btc and eth.
> add get free addresses endpoint for registration service

- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcFullPipelineTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcNotaryIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcWithdrawalIntegrationTest.kt
- notary-iroha-integration-test/src/main/kotlin/integration/helper/IrohaIntegrationHelperUtil.kt
Two integration tests were added:
1) Multithreaded Bitcoin deposit
2) Multithreaded Bitcoin withdrawal(see full pipeline test)
> New bitcoin multithreaded tests

- deploy/docker-compose-single.yml
> add ports to docker compose

- README.md
Completes README with a new service
> Add rmq to README

- btc-deposit/src/main/kotlin/notary/btc/init/BtcNotaryInitialization.kt
- btc-deposit/src/main/kotlin/notary/btc/listener/BitcoinBlockChainDepositListener.kt
- btc-deposit/src/main/kotlin/notary/btc/listener/BitcoinTransactionListener.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcFullPipelineTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcMultiNotaryIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcNotaryTestEnvironment.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcWithdrawalTestEnvironment.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcConfigHelper.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcIntegrationHelperUtil.kt
- notary-iroha-integration-test/src/main/kotlin/integration/helper/IrohaAccountHelper.kt
- notary-iroha-integration-test/src/main/kotlin/integration/helper/IrohaIntegrationHelperUtil.kt
New Bitcoin deposit test with 3 deposit 'nodes' and multisignature notary account.
> Bitcoin multisig notary test

- btc-deposit/src/main/kotlin/notary/btc/init/BtcNotaryInitialization.kt
- btc/src/main/kotlin/com/d3/btc/provider/generation/BtcPublicKeyProvider.kt
- deploy/iroha/genesis.block
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcMultiAddressGenerationIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcAddressGenerationTestEnvironment.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcConfigHelper.kt
- notary-commons/src/main/kotlin/sidechain/iroha/util/ModelUtil.kt
- notary-iroha-integration-test/src/main/kotlin/integration/helper/IrohaAccountHelper.kt
Now we have multisig address generation test
> bitcoin address generation multisig test

- btc-registration/build.gradle
- btc-registration/src/main/kotlin/com/d3/btc/registration/config/BtcRegistrationAppConfiguration.kt
- btc-registration/src/main/kotlin/com/d3/btc/registration/config/BtcRegistrationConfig.kt
- btc-registration/src/main/kotlin/com/d3/btc/registration/init/BtcRegistrationServiceInitialization.kt
- btc-registration/src/main/kotlin/com/d3/btc/registration/main.kt
- btc-registration/src/main/kotlin/com/d3/btc/registration/strategy/BtcRegistrationStrategyImpl.kt
- deploy/docker-compose-single.yml
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcRegistrationTestEnvironment.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcConfigHelper.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcIntegrationHelperUtil.kt
Changed `btc-registration` package. Now it's `com.d3.btc.registration`
> Btc registration renamed package

- btc-dw-bridge/src/main/kotlin/dwbridge/btc/config/BtcDWBridgeAppConfiguration.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/config/BtcWithdrawalAppConfiguration.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/config/BtcWithdrawalConfig.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/transaction/BtcRollbackService.kt
- configs/btc/withdrawal_local.properties
- configs/btc/withdrawal_mainnet.properties
- configs/btc/withdrawal_testnet.properties
- deploy/iroha/genesis.block
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcMultiWithdrawalIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcWithdrawalIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcWithdrawalTestEnvironment.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcConfigHelper.kt
- notary-commons/src/main/kotlin/sidechain/iroha/util/ModelUtil.kt
- notary-iroha-integration-test/src/main/kotlin/integration/helper/IrohaAccountHelper.kt
- notary-iroha-integration-test/src/main/kotlin/integration/helper/IrohaIntegrationHelperUtil.kt
Fixed rollback service. There was no quorum set, but now it's ok. Plus new multisig rollback test.
> Fixed Btc withdrawal rollback

- btc-address-generation/build.gradle
- btc-address-generation/src/main/kotlin/com/d3/btc/generation/config/BtcAddressGenerationAppConfiguration.kt
- btc-address-generation/src/main/kotlin/com/d3/btc/generation/config/BtcAddressGenerationConfig.kt
- btc-address-generation/src/main/kotlin/com/d3/btc/generation/init/BtcAddressGenerationInitialization.kt
- btc-address-generation/src/main/kotlin/com/d3/btc/generation/main.kt
- btc-address-generation/src/main/kotlin/com/d3/btc/generation/trigger/AddressGenerationTrigger.kt
- btc-address-generation/src/main/kotlin/com/d3/btc/generation/trigger/BtcAddressGenerationTriggerAppConfiguration.kt
- btc-address-generation/src/main/kotlin/com/d3/btc/generation/trigger/ChangeAddressGeneration.kt
- btc-address-generation/src/main/kotlin/com/d3/btc/generation/trigger/FreeAddressGeneration.kt
- deploy/docker-compose-full.yml
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcAddressGenerationTestEnvironment.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcConfigHelper.kt
New `btc-address-generation` module package naming. Now it's `com.d3.btc.generation`
> Bitcoin generation renamed package

- eth/build.gradle
- eth/src/main/java/contract/RelayRegistry.java
- notary-eth-integration-test/src/integration-test/kotlin/integration/eth/contracts/MasterTest.kt
Fix tests after master contract upgrade.
> fix master contract tests

- btc-address-generation/src/main/kotlin/com/d3/btc/generation/init/BtcAddressGenerationInitialization.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/init/BtcWithdrawalInitialization.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/listener/BitcoinFeeRateListener.kt
- btc/src/main/kotlin/com/d3/btc/provider/generation/BtcPublicKeyProvider.kt
- deploy/docker-compose-base.yml
- deploy/docker-compose.yml
- deploy/iroha/config.docker
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcMultiAddressGenerationIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcAddressGenerationTestEnvironment.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcWithdrawalTestEnvironment.kt
- notary-commons/build.gradle
- notary-commons/src/main/kotlin/sidechain/iroha/consumer/IrohaConsumerImpl.kt
- notary-commons/src/main/kotlin/sidechain/iroha/util/RequestHelper.kt
- notary-eth-integration-test/src/integration-test/kotlin/integration/eth/WithdrawalPipelineIntegrationTest.kt
> Migration to RC3

- chain-adapter/build.gradle
- chain-adapter/src/main/kotlin/com/d3/chainadapter/ChainAdapter.kt
- chain-adapter/src/main/kotlin/com/d3/chainadapter/main.kt
- chain-adapter/src/main/resources/log4j.properties
- deploy/docker-compose-base.yml
- deploy/docker-compose.yml
Changed `chain-adapter` module packaging. Now it's `com.d3.chainadapter`
> Chain-adapter renamed packaging

- configs/eth/predeploy_local.properties
- configs/eth/predeploy_mainnet.properties
- configs/eth/predeploy_testnet.properties
Increase gas limit in order to
> fix predeploy gas limit

- btc-dw-bridge/build.gradle
- btc-dw-bridge/src/main/kotlin/com/d3/btc/dwbridge/config/BtcDWBridgeAppConfiguration.kt
- btc-dw-bridge/src/main/kotlin/com/d3/btc/dwbridge/config/BtcDWBridgeConfig.kt
- btc-dw-bridge/src/main/kotlin/com/d3/btc/dwbridge/main.kt
- deploy/docker-compose-full.yml
Renamed `btc-dw-bridge` module package. Now it's `com.d3.btc.dwbridge`
> Btc dw-bridge renamed packaging

- configs/eth/predeploy_local.properties
- configs/eth/predeploy_mainnet.properties
- configs/eth/predeploy_testnet.properties
More gas for the Ethereum deploy.
> Add gas to predeploy

- notary-commons/src/main/kotlin/sidechain/iroha/ReliableIrohaChainListener.kt
`source.onNext()` is called before any subscription. It causes block losses. We must wait until the first subscription before producing events.
> Fixed RMQ chain subscribe

- eth-withdrawal/src/main/kotlin/withdrawalservice/WithdrawalServiceImpl.kt
- eth-withdrawal/src/main/kotlin/withdrawalservice/WithdrawalServiceInitialization.kt
Log init parameters on startup.
> add withdrawal init logging

- deploy/docker-compose-base.yml
- deploy/docker-compose.yml
- notary-commons/build.gradle
> RC4 migration

- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcFullPipelineTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcMultiNotaryIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcMultiWithdrawalIntegrationTest.kt
Few Bitcoin tests were disabled. This is temporary. Tests will be fixed soon.
> Disabled BTC tests

- btc/build.gradle
Fixed CLI packages in gradle tasks
> Fixed BTC cli packages

- .gitignore
- chain-adapter-integration-test/build.gradle
- chain-adapter-integration-test/src/integration-test/kotlin/integration/chainadapter/ChainAdapterIntegrationTest.kt
- chain-adapter-integration-test/src/integration-test/kotlin/integration/chainadapter/ChainAdapterUnreadIntegrationTest.kt
- chain-adapter-integration-test/src/integration-test/kotlin/integration/chainadapter/environment/ChainAdapterIntegrationTestEnvironment.kt
- chain-adapter-integration-test/src/integration-test/resources/log4j.properties
- chain-adapter-integration-test/src/main/kotlin/integration/helper/ChainAdapterConfigHelper.kt
- chain-adapter/build.gradle
- chain-adapter/src/main/kotlin/com/d3/chainadapter/adapter/ChainAdapter.kt
- chain-adapter/src/main/kotlin/com/d3/chainadapter/main.kt
- chain-adapter/src/main/kotlin/com/d3/chainadapter/provider/FileBasedLastReadBlockProvider.kt
- chain-adapter/src/main/kotlin/com/d3/chainadapter/provider/LastReadBlockProvider.kt
- configs/rmq.properties
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcMultiAddressGenerationIntegrationTest.kt
- notary-commons/src/main/kotlin/com/d3/commons/config/Configs.kt
- notary-commons/src/main/kotlin/com/d3/commons/sidechain/iroha/ReliableIrohaChainListener.kt
- notary-commons/src/main/kotlin/com/d3/commons/sidechain/iroha/util/RequestHelper.kt
- notary-iroha-integration-test/src/main/kotlin/integration/helper/IrohaAccountHelper.kt
- notary-iroha-integration-test/src/main/kotlin/integration/helper/IrohaIntegrationHelperUtil.kt
- settings.gradle
Fail tolerant `chain-adapter`. It saves the last read block height in a file and proceeds its job after restart right from the last read block.
> Fail tolerant chain-adapter

- eth-registration/src/main/kotlin/com/d3/eth/registration/relay/RelayRegistration.kt
Catch exception in relay registration.
> fix RelayRegistration exception handling

- notary-registration/src/main/kotlin/com/d3/commons/registration/main.kt
Fix package, so it is possible to run
```./gradlew runRegistration```
> fix package name in registration service

- deploy/docker-compose.yml
> allow any rpc ip in btc node

- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/transaction/SignCollector.kt
A newly added node will not be able to sign transactions with an address that was generated without newly added node participation. There is no need to throw an exception if a node cannot sign a transaction anymore.
> Fixed signature check

- .gitignore
- bootstrap/build.gradle
- btc-address-generation/build.gradle
- btc-dw-bridge/build.gradle
- btc-registration/build.gradle
- build.gradle
- notary-registration/build.gradle
It's time for D3 to be accessible via [jitpack](https://jitpack.io/)
> Prepare for jitpack

- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/controller/BtcController.kt
- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/controller/IrohaController.kt
- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/dto/Model.kt
- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/exceptions/Exceptions.kt
- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/genesis/GenesisInterface.kt
- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/genesis/d3/D3TestContext.kt
- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/genesis/d3/D3TestGenesisFactory.kt
- bootstrap/src/test/kotlin/jp/co/soramitsu/bootstrap/IrohaTest.kt
Quorum returned by /iroha/config/accounts/{project}/{env} endpoint does not consider number of Iroha peers #426
> Bootstrap service

- README.md
- notifications/src/main/kotlin/com/d3/notifications/service/EmailNotificationService.kt
- notifications/src/main/kotlin/com/d3/notifications/smtp/SMTPServiceImpl.kt
Now we can send emails using AWS SES
> AWS SES Integration

- btc-deposit/README.md
Updated Bitcoin deposit service documentation
> Bitcoin deposit documentation

- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/handler/NewSignatureEventHandler.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/handler/NewTransferHandler.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/service/BtcRollbackService.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/service/WithdrawalTransferService.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcWithdrawalTestEnvironment.kt
It's quite confusing for a client to see plain 'rollback' message. It would be nice to add some details.
> Rollback details

- btc-address-generation/README.md
- btc-address-generation/src/main/kotlin/com/d3/btc/generation/config/BtcAddressGenerationConfig.kt
- btc/src/main/kotlin/com/d3/btc/provider/generation/BtcPublicKeyProvider.kt
Bitcoin Address Generation service documentation.
> Bitcoin address generation documentation

- btc-deposit/README.md
- btc-withdrawal/README.md
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/service/WithdrawalTransferService.kt
- configs/btc/withdrawal_local.properties
- configs/btc/withdrawal_mainnet.properties
- configs/btc/withdrawal_testnet.properties
Bitcoin withdrawal service documentation
> Btc withdrawal documentation

- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/handler/NewTransferHandler.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/service/WithdrawalTransferService.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcWithdrawalTestEnvironment.kt
Bitcoin withdrawal service works this way:
1) Create 'withdrawal consensus'
2) Check if withdrawal is valid
3) Create Bitcoin withdrawal transaction 
4) And so on...
Steps 1 and 2 must be swapped because we may create 'withdrawal consensus' for invalid withdrawal operation.
> Fixed Bitcoin withdrwal checks

- configs/brvs/application.properties
- configs/brvs/spring-context.xml
Since there is no more auto registration of new bras instance we should update the configs
> Updated BRVS configs

- btc-deposit/README.md
Bitcoin deposit service grammar improvement.  Checked by Sara
> Improved BTC deposit documentation

- README.md
- deploy/docker-compose-full.yml
- deploy/docker-compose-single.yml
- deploy/docker-compose.yml
Add jar filename for docker-compose.
> fix docker jar name

- bootstrap/build.gradle
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/transaction/consensus/ConsensusDataStorage.kt
- deploy/docker-compose-base.yml
- deploy/docker-compose.yml
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcMultiWithdrawalIntegrationTest.kt
- notary-commons/build.gradle
> Moving to RC5

- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/provider/BtcChangeAddressProvider.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/transaction/SignCollector.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/transaction/TransactionSigner.kt
- btc/src/main/kotlin/com/d3/btc/provider/generation/BtcPublicKeyProvider.kt
> New logs in Bitcoin services

- bootstrap/src/integration-test/kotlin/jp/co/soramitsu/bootstrap/ChangelogIntegrationTest.kt
- bootstrap/src/integration-test/resources/log4j.properties
- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/changelog/history/ChangelogHistoryService.kt
- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/changelog/service/ChangelogExecutor.kt
- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/genesis/d3/D3TestContext.kt
- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/iroha/IrohaAPIExt.kt
- deploy/bootstrap/changelogs/sample_changelog.groovy
- deploy/iroha/genesis.block
Now we are able to store changelog history in Iroha. Every changelog transaction is accompanied by changelog history transaction. This transaction combination forms an atomic batch. All the information is stored in `changelog_history@bootstrap` details (`shemaVersion`->`changelog reducedTxHash`)
> Bootstrap history

- configs/brvs/spring-context.xml
> Added env variables resolving

- .gitignore
- configs/brvs/application.properties
- configs/brvs/spring-context.xml
- exchanger/src/integration-test/kotlin/com/d3/exchange/util/ExchangerServiceTestEnvironment.kt
- notary-iroha-integration-test/src/integration-test/kotlin/integration/iroha/IrohaBatchTest.kt
- notary-iroha-integration-test/src/integration-test/kotlin/integration/iroha/IrohaBlockStreamingTest.kt
> Updated brvs config

- bootstrap/src/integration-test/kotlin/jp/co/soramitsu/bootstrap/ChangelogIntegrationTest.kt
- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/changelog/helper/ChangelogHelper.kt
- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/changelog/service/ChangelogExecutor.kt
Now the changelog service is idempotent(the same changelog may be applied only once).
> Idempotent changelog service

- README.md
- btc-address-generation/README.md
- btc-address-generation/src/main/kotlin/com/d3/btc/generation/config/BtcAddressGenerationAppConfiguration.kt
- btc-address-generation/src/main/kotlin/com/d3/btc/generation/init/BtcAddressGenerationInitialization.kt
- btc-address-generation/src/main/kotlin/com/d3/btc/generation/trigger/AddressGenerationTrigger.kt
- btc-deposit/src/main/kotlin/com/d3/btc/deposit/listener/BitcoinBlockChainDepositListener.kt
- btc-dw-bridge/src/main/kotlin/com/d3/btc/dwbridge/config/BtcDWBridgeAppConfiguration.kt
- btc-withdrawal/README.md
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/config/BtcWithdrawalAppConfiguration.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/handler/NewChangeAddressHandler.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/handler/NewConsensusDataHandler.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/init/BtcWithdrawalInitialization.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/provider/WithdrawalConsensusProvider.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/transaction/TransactionCreator.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/transaction/TransactionHelper.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/transaction/TransactionSigner.kt
- btc-withdrawal/src/test/java/com/d3/btc/withdrawal/transaction/TransactionHelperTest.java
- btc/src/main/kotlin/com/d3/btc/provider/BtcChangeAddressProvider.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcAddressGenerationIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcFullPipelineTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcMultiAddressGenerationIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcMultiWithdrawalIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcAddressGenerationTestEnvironment.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcWithdrawalTestEnvironment.kt
Now Bitcoin change addresses are generated automatically. `btc-address-generation` generates in on start.
> Bitcoin auto change address generation

- deploy/docker-compose-base.yml
- deploy/docker-compose.yml
Chain-adapter will be restarted automatically if the process returns a non-zero value on exit.
> Chain-adapter auto-restart

- configs/changelog/changelog.properties
- deploy/docker-compose-single.yml
Adding the changelog service to D3 project
> Changelog integration

- eth-registration/src/main/kotlin/com/d3/eth/registration/EthRegistrationStrategyImpl.kt
- notary-commons/src/main/kotlin/com/d3/commons/registration/RegistrationServiceEndpoint.kt
- notary-commons/src/test/java/com/d3/commons/registration/IrohaAccountRegistratorTest.java
In order to integrate with Sora we need to provide JSON friendly registration endpoint. Also whitelists have been removed.
> Added json endpoint, removed whitelists

- Jenkinsfile
- deploy/docker-compose-single.yml
- docker/v1/dockerfile
- notifications/build.gradle
The notifications service dockerization.
> Notifications service Docker integration

- notary-commons/build.gradle
- notary-commons/src/test/kotlin/com/d3/commons/config/ConfigsPriorityTest.kt
The library maintainer has fixed the issue recently
> Updated cfg4k env issue since it got fixed

- exchanger/src/integration-test/kotlin/com/d3/exchange/util/ExchangerServiceTestEnvironment.kt
- exchanger/src/main/kotlin/com/d3/exchange/exchanger/ExchangerAppConfiguration.kt
- exchanger/src/main/kotlin/com/d3/exchange/exchanger/ExchangerService.kt
- notary-commons/src/main/kotlin/com/d3/commons/sidechain/iroha/ReliableIrohaChainListener.kt
- notary-iroha-integration-test/src/integration-test/kotlin/integration/iroha/IrohaBatchTest.kt
- notary-iroha-integration-test/src/integration-test/kotlin/integration/iroha/IrohaBlockStreamingTest.kt
- notary-iroha-integration-test/src/main/kotlin/integration/helper/IrohaIntegrationHelperUtil.kt
Fixed `ReliableIrohaChainListener`. Now you have to define subscribers and call `listen()` function afterward.
> Truly reliable Iroha chain listener

- deploy/iroha/genesis.block
> Fix deposit service url in genesis

- notary-iroha-integration-test/src/main/kotlin/integration/helper/ContainerHelper.kt
Now all the test containers inside the `ContainerHelper` class are created lazily.
> Lazy ContainerHelper

- Jenkinsfile
Signed-off-by: Bulat Saifullin <bulat@saifullin.ru>
change sh to bash in jenkins script
> Fix jenkins shell

- notary-commons/src/main/kotlin/com/d3/commons/sidechain/iroha/util/RequestHelper.kt
New function` getCreateAccountCommands()`. It may be used to get 'create account' commands out of Iroha block. Very useful.
> New getCreateAccountCommands function

- notary-iroha-integration-test/src/main/kotlin/integration/helper/ContainerHelper.kt
Added new function that creates sora-plugin based docker containers.
> Sora-plugin container creator

- Jenkinsfile
- deploy/docker-compose-single.yml
- exchanger/build.gradle
- exchanger/settings.gradle
- notary-registration/build.gradle
- notary-registration/settings.gradle
- notifications/build.gradle
- notifications/settings.gradle
> sora-plugin integration

- deploy/docker-compose.dev.yml
set BRVS validation time to 10 sec
> set BRVS validation time to 10 sec

- notary-commons/src/main/kotlin/com/d3/commons/sidechain/iroha/ReliableIrohaChainListener.kt
> Possible to omit default values of chain listener in Java

- bootstrap/build.gradle
> Fixed shadowjar

- bootstrap/build.gradle
- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/controller/EthController.kt
- deploy/iroha/genesis.block
- exchanger/src/integration-test/kotlin/com/d3/exchange/ExchangerIntegrationTest.kt
- exchanger/src/main/kotlin/com/d3/exchange/exchanger/ExchangerService.kt
- notary-iroha-integration-test/src/main/kotlin/integration/helper/IrohaIntegrationHelperUtil.kt
- notary-sora-integration-test/src/integration-test/kotlin/integration/sora/SoraIntegrationTest.kt
> Update eth lib version

- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/controller/IrohaController.kt
> fix negative peer

- notary-commons/src/main/kotlin/com/d3/commons/registration/RegistrationServiceEndpoint.kt
- notary-iroha-integration-test/src/main/kotlin/integration/helper/IrohaConfigHelper.kt
- notary-registration/src/main/kotlin/com/d3/commons/registration/NotaryRegistrationConfig.kt
- notary-registration/src/main/kotlin/com/d3/commons/registration/RegistrationServiceInitialization.kt
- notary-registration/src/main/resources/registration.properties
> Made registration domain dependent

- exchanger/src/main/kotlin/com/d3/exchange/exchanger/ExchangerAppConfiguration.kt
- exchanger/src/main/kotlin/com/d3/exchange/exchanger/ExchangerConfig.kt
- notary-commons/src/main/kotlin/com/d3/commons/model/IrohaCredential.kt
- notary-commons/src/main/kotlin/com/d3/commons/sidechain/iroha/util/impl/IrohaQueryHelperImpl.kt
- notary-iroha-integration-test/src/main/kotlin/integration/helper/IrohaAccountHelper.kt
- notary-iroha-integration-test/src/main/kotlin/integration/registration/RegistrationServiceTestEnvironment.kt
- notary-registration/src/main/kotlin/com/d3/commons/registration/NotaryRegistrationAppConfiguration.kt
- notary-registration/src/main/kotlin/com/d3/commons/registration/NotaryRegistrationConfig.kt
- notifications/src/main/kotlin/com/d3/notifications/config/NotificationAppConfiguration.kt
- notifications/src/main/kotlin/com/d3/notifications/config/NotificationsConfig.kt
Rework IrohaCredentials - add new constructor from config.
> rework IrohaCredential

- notary-commons/src/main/kotlin/com/d3/commons/sidechain/iroha/util/IrohaQueryHelper.kt
- notary-commons/src/main/kotlin/com/d3/commons/sidechain/iroha/util/impl/IrohaQueryHelperImpl.kt
> GetAccountDetails by key

- notary-commons/src/main/kotlin/com/d3/commons/registration/RegistrationServiceEndpoint.kt
Before there was a way to pass an empty domain and registration wouldn't work when it was expected to
> Fixed domain priority

- notary-iroha-integration-test/src/main/kotlin/integration/helper/IrohaAccountHelper.kt
> Making createTesterAccount() public

- notary-commons/src/main/kotlin/com/d3/commons/registration/RegistrationServiceEndpoint.kt
> Only null check for pubkey

- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/genesis/d3/D3TestContext.kt
> Added admin permissions
