- iroha_bindings.sh
Add missed protobuf library for Linux platform.
Also, we have to merge https://github.com/hyperledger/iroha/pull/1289 to our subtree.
> Add protobuf so copy for linux platform

- build.gradle
- src/test/kotlin/vendor/moshi.kt
Add Moshi library for working with JSON format.
JSON is required for performing refund requests.
> Add library for JSON

- src/main/kotlin/endpoint/RefundServerEndpoint.kt
- src/main/kotlin/util/functional/bind.kt
- src/test/util/functional/BindTest.kt
Resolving of the extension function is broken in Kotlin.
Our `map` and `map` for collections isn't resolved properly.
The solution is just to rename our `map` to `bind`.
> Rename map to bind

- src/main/kotlin/sidechain/iroha/consumer/IrohaConverterImpl.kt
- src/test/kotlin/registration/RegistrationTest.kt
Previously it was assumed to send byte representation, now fixed to string representation.
> fix pubkey size sent to Iroha

- src/test/integration/ContractsTest.kt
Cases covered:
- Not enough tokens to withdraw
- Not enough ether to withdraw
- Not enough signatures provided
- No peers were added
- V, r and s arrays are not the same size
- Two exactly the same signatures provided (this one should be handled by contract differently)
- Signature is invalid
- Two different peers were added
- One peer was added twice
> Add bunch of contracts tests

- src/main/kotlin/notary/NotaryInitialization.kt
- src/main/kotlin/sidechain/eth/EthChainHandler.kt
- src/test/integration/IntegrationTest.kt
- src/test/kotlin/notary/NotaryInitializationTest.kt
Fix notary.
Previously provider returns the list of observable wallets and tokens on start, now we query each time eht block arrives.
> fix getWallets in notary

- deploy-relay.dockerfile
- notary.dockerfile
- registration.dockerfile
- withdrawal.dockerfile
Since `library/gradle` does not work, I built it from Dockerfile and uploaded on docker hub.
> Temporary fix for gradle image

- src/integration-test/kotlin/integration/eth/WithdrawalPipelineIntegrationTest.kt
- src/integration-test/kotlin/integration/helper/ConfigHelper.kt
- src/main/kotlin/notary/NotaryImpl.kt
- src/main/kotlin/registration/eth/EthRegistrationServiceInitialization.kt
- src/test/kotlin/notary/NotaryTest.kt
Remove CreateAsset from notary deposit pipeline.
Fix integration test configs.
> remove createAsset from notary logic

- src/integration-test/kotlin/integration/eth/ContractsTest.kt
- src/integration-test/resources/test.properties
- src/integration-test/resources/test_deploy.properties
Now we have tests for withdrawal with many peers and many signatures. Also tests code was refactored a bit.
> Add withdrawal tests for cases with many peers

- notary-integration-test/src/integration-test/kotlin/integration/iroha/IrohaBlockStreamingTest.kt
- src/main/kotlin/sidechain/ChainListener.kt
- src/main/kotlin/sidechain/eth/EthChainListener.kt
- src/main/kotlin/sidechain/iroha/IrohaChainListener.kt
ChainListener should be closeable because it acquires some resources.
This PR implements this interface for Ethereum and Iroha
> Implement closeable in Eth and Iroha chain listeners

- btc-deposit/src/main/kotlin/notary/btc/BtcNotaryInitialization.kt
- btc-deposit/src/main/kotlin/notary/btc/config/BtcNotaryAppConfiguration.kt
- btc-deposit/src/main/kotlin/notary/btc/listener/BitcoinBlockChainListener.kt
- btc-registration/src/main/kotlin/registration/btc/BtcRegistrationServiceInitialization.kt
- btc-registration/src/main/kotlin/registration/btc/BtcRegistrationStrategyImpl.kt
- btc-registration/src/main/kotlin/registration/btc/config/BtcRegistrationAppConfiguration.kt
- btc-registration/src/main/kotlin/registration/btc/config/BtcRegistrationConfig.kt
- btc-registration/src/main/kotlin/registration/btc/main.kt
- btc-registration/src/main/resources/application.yml
- btc/src/main/kotlin/provider/btc/BtcSessionProvider.kt
- btc/src/main/kotlin/provider/btc/address/BtcAddressesProvider.kt
- btc/src/main/kotlin/provider/btc/address/BtcRegisteredAddressesProvider.kt
- configs/btc/registration_local.properties
- configs/btc/registration_testnet.properties
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcNotaryIntegrationTest.kt
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcRegistrationIntegrationTest.kt
- notary-integration-test/src/main/kotlin/integration/helper/ConfigHelper.kt
- notary-integration-test/src/main/kotlin/integration/helper/IntegrationHelperUtil.kt
- src/main/kotlin/registration/IrohaAccountCreator.kt
Now BTC registration service is also based on Spring Framework, but web-service is still working using Netty. It will be reimplemented after we move all the project services to Spring.
> BTC registration service based on Spring framework

- configs/btc/notary_local.properties
- configs/btc/notary_testnet.properties
- src/main/kotlin/config/ConfigValidator.kt
- src/main/kotlin/config/Configs.kt
- src/test/kotlin/config/ConfigValidationTest.kt
- src/test/kotlin/config/ConfigsPriorityTest.kt
- src/test/kotlin/config/TestConfig.kt
Now we can set validation rules for an arbitrary configuration. By the contract(see ConfigValidationRule) validation rule must throw IllegalArgumentException if configuration violates validation logic.
> Validation rules for configurations

- deploy/docker-compose-base.yml
- deploy/docker-compose-full.yml
- deploy/docker-compose-single.yml
This PR adds some flexibility for deploying our services.
If we want to run a full node, with all the services:
` PROFILE=testnet TAG=debug docker-compose -f deploy/docker-compose-base.yml -f deploy/docker-compose-full.yml -f deploy/docker-compose-single.yml  up`
To run only the services that have to be deployed on each node of the network
`PROFILE=testnet TAG=debug docker-compose -f deploy/docker-compose-base.yml -f deploy/docker-compose-full.yml  up`
To run only the services that have to deployed only once per network:
`PROFILE=testnet TAG=debug docker-compose -f deploy/docker-compose-base.yml -f deploy/docker-compose-single.yml  up`
> Split compose file

- btc-deposit/src/main/kotlin/notary/btc/config/BtcNotaryAppConfiguration.kt
This pr shows how easely IrohaNetwork may be closed using Spring framework. No actions required, because Spring closes Closeables by itself.
> Closing IrohaNetwork using Spring

- .gitignore
- notary-integration-test/src/main/kotlin/integration/helper/ConfigHelper.kt
We had a problem with bitcoin wallet file being tracked by git even with well configured `.gitignore`. Git tracks wallet file because it was commited in the past. We cannot remove this file, because it's needed to run integration tests. The simpliest workaround is creating ignored temporary copy of wallet file every time we run bitcoin tests.
> Bitcoin wallet is ignored

- btc-deposit/src/main/kotlin/notary/btc/BtcNotaryInitialization.kt
- btc-deposit/src/main/kotlin/notary/btc/config/BtcNotaryAppConfiguration.kt
- btc-pregeneration/src/main/kotlin/pregeneration/btc/BtcPreGenInitialization.kt
- configs/btc/notary_local.properties
- configs/btc/notary_testnet.properties
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcNotaryIntegrationTest.kt
- src/main/kotlin/sidechain/iroha/util/RequestHelper.kt
Newly registered BTC addresses were not visible to deposit service.  Now we have a dedicated listener that listens to registration events in Iroha.
> BTC registration and deposit services synchronization

- btc-withdrawal/src/main/kotlin/withdrawal/btc/BtcWithdrawalInitialization.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/config/BtcWithdrawalAppConfiguration.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/handler/NewSignatureEventHandler.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/handler/WithdrawalTransferEventHandler.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/provider/BtcWhiteListProvider.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/transaction/SignCollector.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/transaction/TimedTx.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/transaction/TransactionCreator.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/transaction/TransactionHelper.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/transaction/TransactionSigner.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/transaction/UnsignedTransactions.kt
- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcWithdrawalIntegrationTest.kt
Now we can sign withdrawal transactions and send it to Bitcoin network. Also a little refactor was made:
1) Handler functions are moved from `BtcWithdrawalInitialization` to dedicated classes: `NewSignatureEventHandler` and `WithdrawalTransferEventHandler`
2) Package structure is fixed
> Sending transactions into Bitcoin network

- notary-integration-test/src/integration-test/kotlin/integration/btc/BtcWithdrawalIntegrationTest.kt
- notary-integration-test/src/main/kotlin/integration/helper/IntegrationHelperUtil.kt
Address pregeneration in tests takes too much time. We can make it a lot faster using batched transactions.
> Batched address generation

- btc-deposit/src/main/kotlin/notary/btc/BtcNotaryInitialization.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/BtcWithdrawalInitialization.kt
- btc/src/main/kotlin/helper/network/BitcoinNetworkHelper.kt
Peer group status listener was added in withdrawal service. It changes the status of service to "unhealthy" if no peers left in a peer group. It also changes the status to "healthy" if new peer connected.
> Peer group status listener in withdrawal service

- btc-deposit/src/main/kotlin/notary/btc/BtcNotaryInitialization.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/BtcWithdrawalInitialization.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcWithdrawalTestEnvironment.kt
There is a need to add previously registered addresses to wallet's watched addresses. Otherwise, some deposit and withdrawal events may be out of sync.
> Watched bitcoin addresses

- btc-deposit/src/main/kotlin/notary/btc/listener/BitcoinTransactionListener.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/handler/WithdrawalTransferEventHandler.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/send/SendBtc.kt
- btc/src/main/kotlin/helper/currency/BtcSatConverter.kt
- deploy/iroha/genesis.block
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcFullPipelineTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcNotaryIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcWithdrawalIntegrationTest.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcIntegrationHelperUtil.kt
- notary-iroha-integration-test/src/main/kotlin/integration/helper/IrohaIntegrationHelperUtil.kt
`btc#bitcoin` precision was changed from 0 to 8, meaning that Iroha will store Bitcoin values instead of Satoshi.
> Fixed Bitcoin precision

- btc/build.gradle
Spring Boot plugin adds a task called `bootRepackage` that packages spring project into an executable jar file. `btc` is a library project with no main class, meaning that it cannot be executed directly. That's why we don't need this task in this project.
> Boot repackage was disabled

- btc-address-generation/src/main/kotlin/generation/btc/init/BtcAddressGenerationInitialization.kt
- btc-address-generation/src/main/kotlin/generation/btc/trigger/AddressGenerationTrigger.kt
- btc-deposit/src/main/kotlin/notary/btc/init/BtcNotaryInitialization.kt
- btc/src/main/kotlin/provider/btc/generation/BtcPublicKeyProvider.kt
- btc/src/main/kotlin/provider/btc/generation/BtcSessionProvider.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcAddressGenerationIntegrationTest.kt
- notary-commons/src/main/kotlin/sidechain/iroha/util/ModelUtil.kt
- notary-commons/src/main/kotlin/sidechain/iroha/util/RequestHelper.kt
We use Iroha multisig transactions to create Bitcoin addresses. A previous source of time was a node time, meaning that multisig will never be succeeded because it will have different hash value on different nodes. Now we set time at caller level before address generation process starts. Those who starts address generation process also sets a time for a current address generation session. This time will be used by multiple nodes.
> Bitcoin multisig address safe time source

- btc-withdrawal/src/main/kotlin/withdrawal/btc/transaction/SignCollector.kt
Two nodes cannot perform a withdrawal transaction simultaneously, because every node will try to create "tx signature storage" account. Only one account creation command will be successfully committed. So we have to ignore account creation command exceptions.
> Ignoring failed Iroha account creation command

- btc-deposit/src/main/kotlin/notary/btc/init/BtcNotaryInitialization.kt
- btc/src/main/kotlin/listener/btc/NewBtcClientRegistrationListener.kt
We have to kill deposit service if Iroha is not functioning.  Otherwise, deposit events will not be handled by Iroha. This situation may cause money loss.
> Kill deposit if Iroha is not functioning

- Jenkinsfile
Add -p option to mkdir to be able complete build-logs task even if directory exists.
See build log error:
```
+ mkdir build-logs
mkdir: cannot create directory ‘build-logs’: File exists
Terminated
script returned exit code 1
```
See https://jenkins.soramitsu.co.jp/blue/organizations/jenkins/d3%2Fd3-notary/detail/update_xor_token/4/pipeline/
> fix mkdir build-logs in Jenkins

- btc-address-generation/src/main/kotlin/generation/btc/config/BtcAddressGenerationConfig.kt
- btc-address-generation/src/main/kotlin/generation/btc/init/BtcAddressGenerationInitialization.kt
- btc-address-generation/src/main/kotlin/generation/btc/main.kt
- btc-address-generation/src/main/kotlin/generation/btc/trigger/AddressGenerationTrigger.kt
- btc-address-generation/src/main/kotlin/generation/btc/trigger/BtcAddressGenerationTriggerAppConfiguration.kt
- btc/src/main/kotlin/provider/btc/account/IrohaBtcAccountCreator.kt
- btc/src/main/kotlin/provider/btc/address/BtcFreeAddressesProvider.kt
- btc/src/main/kotlin/provider/btc/generation/BtcSessionProvider.kt
- configs/btc/address_generation_local.properties
- configs/btc/address_generation_mainnet.properties
- configs/btc/address_generation_testnet.properties
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcAddressGenerationIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcFullPipelineTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcWithdrawalIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcAddressGenerationTestEnvironment.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcConfigHelper.kt
- notary-commons/src/main/kotlin/provider/TriggerProvider.kt
Now BTC addresses can be generated automatically. There are two cases that may trigger this process:
1) Address generation process was started for the first time
2) New client was registered
> Automatic BTC addresses generation

- README.md
- btc/build.gradle
- btc/src/main/kotlin/cli/BtcNodeRpcConfig.kt
- btc/src/main/kotlin/cli/GenerateBlocks.kt
- btc/src/main/kotlin/cli/SendToAddress.kt
- configs/btc/node-rpc_local.properties
- notary-btc-integration-test/build.gradle
Now we can send Bitcoins and generate blocks with no bitcoin-cli or bitcoind being involved. 
Usage:
1) Generate blocks `./gradlew btcGenerateBlocks -Pblocks=<blocks>` 
2) Send to address `./gradlew btcSendToAddress -Paddress=<address> -PamountBtc=<amountBtc>` (no need to generate 6 blocks after that)
> Bitcoin-cli in gradle

- .gitignore
- configs/notifications.properties
- notary-commons/src/main/kotlin/config/Configs.kt
- notary-commons/src/main/kotlin/model/D3Client.kt
- notary-commons/src/main/kotlin/provider/D3ClientProvider.kt
- notary-commons/src/main/kotlin/sidechain/iroha/IrohaVals.kt
- notifications-integration-test/build.gradle
- notifications-integration-test/src/integration-test/kotlin/notifications/NotificationsIntegrationTest.kt
- notifications-integration-test/src/integration-test/kotlin/notifications/environment/NotificationsIntegrationTestEnvironment.kt
- notifications-integration-test/src/integration-test/resources/log4j.properties
- notifications-integration-test/src/main/kotlin/integration/helper/NotificationsConfigHelper.kt
- notifications/build.gradle
- notifications/src/main/kotlin/notifications/config/NotificationAppConfiguration.kt
- notifications/src/main/kotlin/notifications/config/NotificationsConfig.kt
- notifications/src/main/kotlin/notifications/init/NotificationInitialization.kt
- notifications/src/main/kotlin/notifications/main.kt
- notifications/src/main/kotlin/notifications/service/EmailNotificationService.kt
- notifications/src/main/kotlin/notifications/service/NotificationService.kt
- notifications/src/main/kotlin/notifications/smtp/SMTPService.kt
- notifications/src/main/kotlin/notifications/smtp/SMTPServiceImpl.kt
- notifications/src/main/resources/log4j.properties
- settings.gradle
Notifications - is a standalone service dedicated to email notifications. It listens to Iroha blocks and notifies clients if deposit or withdrawal event occurred. We assume that client email is set by himself and stored in account details. 
We also need an SMTP server in order to make this service functioning. SMTP configurations are hidden from VCS since it holds SMTP credentials. But you can use [mailtrap.io](http://mailtrap.io) services for testing purposes(or just ask me, because I've already got mailtrap credentials).
> Email notifications

- .gitignore
- btc-deposit/src/main/kotlin/notary/btc/init/BtcNotaryInitialization.kt
- btc-deposit/src/main/kotlin/notary/btc/listener/BitcoinTransactionListener.kt
- btc-withdrawal/src/main/kotlin/withdrawal/btc/init/BtcWithdrawalInitialization.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcNotaryTestEnvironment.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcWithdrawalTestEnvironment.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcIntegrationHelperUtil.kt
Notary(as well as Withdrawal) service tries to close itself twice: after `IrohaChainListener` failure and in `closeEnvironments()` function. Unfortunately, it causes `Exception` throw. `SharedPeerGroup` may be used instead. It can be stopped multiple times without risk of `Exception` being thrown.
> Fixed peer group close()

- configs/smtp_test.properties
- notifications-integration-test/build.gradle
- notifications-integration-test/src/integration-test/kotlin/notifications/NotificationsIntegrationTest.kt
- notifications-integration-test/src/integration-test/kotlin/notifications/environment/NotificationsIntegrationTestEnvironment.kt
- notifications-integration-test/src/main/kotlin/integration/helper/NotificationsConfigHelper.kt
- notifications/src/main/kotlin/notifications/service/EmailNotificationService.kt
Now we use fake SMTP server called 'Dumbster' right in `notifications` integration tests.
> SMTP dumbster integration test

- configs/btc/registration_local.properties
- configs/btc/registration_mainnet.properties
- configs/btc/registration_testnet.properties
Port `8084` was taken by two services: Ethereum withdrawal and Bitcoin registration. Now Bitcoin registration works using port `8086`.
> Fixed conflicting ports

- btc-address-generation/src/main/kotlin/generation/btc/config/BtcAddressGenerationConfig.kt
- btc-address-generation/src/main/kotlin/generation/btc/init/BtcAddressGenerationInitialization.kt
- btc-address-generation/src/main/kotlin/generation/btc/trigger/AddressGenerationTrigger.kt
- btc-address-generation/src/main/kotlin/generation/btc/trigger/BtcAddressGenerationTriggerAppConfiguration.kt
- btc-address-generation/src/main/kotlin/generation/btc/trigger/ChangeAddressGeneration.kt
- btc-address-generation/src/main/kotlin/generation/btc/trigger/FreeAddressGeneration.kt
- btc-deposit/src/main/kotlin/notary/btc/listener/BitcoinTransactionListener.kt
- btc-registration/src/main/kotlin/com/d3/btc/registration/config/BtcRegistrationAppConfiguration.kt
- btc-registration/src/main/kotlin/com/d3/btc/registration/config/BtcRegistrationConfig.kt
- btc-registration/src/main/kotlin/com/d3/btc/registration/strategy/BtcRegistrationStrategyImpl.kt
- btc/src/main/kotlin/com/d3/btc/model/BtcAddress.kt
- btc/src/main/kotlin/com/d3/btc/provider/BtcFreeAddressesProvider.kt
- btc/src/main/kotlin/com/d3/btc/provider/account/IrohaBtcAccountCreator.kt
- btc/src/main/kotlin/com/d3/btc/provider/generation/BtcPublicKeyProvider.kt
- btc/src/main/kotlin/com/d3/btc/provider/generation/BtcSessionProvider.kt
- configs/btc/address_generation_local.properties
- configs/btc/address_generation_mainnet.properties
- configs/btc/address_generation_testnet.properties
- configs/btc/registration_local.properties
- configs/btc/registration_mainnet.properties
- configs/btc/registration_testnet.properties
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcAddressGenerationIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcFullPipelineTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcMultiAddressGenerationIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcRegistrationIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcAddressGenerationTestEnvironment.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcRegistrationTestEnvironment.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcConfigHelper.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcIntegrationHelperUtil.kt
No more race conditions in Bitcoin registration service. This is how we can approach it:
1) Make registration `synchronized`, so no other thread within node will be able to register the same address
2) Make it able to register node owned addresses only, so no other node with different id will register the same address.
> No more race condition in Btc registration

- chain-adapter/src/main/kotlin/ChainAdapter.kt
According to [AMQP documentation](https://www.rabbitmq.com/tutorials/amqp-concepts.html#queue-durability):
_**Durability of a queue does not make messages that are routed to that queue durable**. If broker is taken down and then brought back up, durable queue will be re-declared during broker startup, however, only persistent messages will be recovered.
Simply publishing a message to a durable exchange or the fact that the queue(s) it is routed to are durable **doesn't make a message persistent**: it all depends on persistence mode of the message itself._
So we need to set persistent mode for every message that goes to the exchange. We can do it using `MessageProperties.MINIMAL_PERSISTENT_BASIC`.
> Forgotten persistency mode

- btc-address-generation/src/main/kotlin/com/d3/btc/generation/init/BtcAddressGenerationInitialization.kt
- btc-deposit/src/main/kotlin/com/d3/btc/deposit/init/BtcNotaryInitialization.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/init/BtcWithdrawalInitialization.kt
- eth-withdrawal/src/main/kotlin/withdrawalservice/WithdrawalServiceInitialization.kt
- notary-commons/src/main/kotlin/sidechain/iroha/IrohaChainListener.kt
- notary-commons/src/main/kotlin/sidechain/iroha/ReliableIrohaChainListener.kt
- notary-iroha-integration-test/src/integration-test/kotlin/integration/iroha/IrohaBatchTest.kt
- notary-iroha-integration-test/src/integration-test/kotlin/integration/iroha/IrohaBlockStreamingTest.kt
- notary-iroha-integration-test/src/main/kotlin/integration/helper/IrohaIntegrationHelperUtil.kt
- notifications-integration-test/src/integration-test/kotlin/notifications/environment/NotificationsIntegrationTestEnvironment.kt
- notifications/src/main/kotlin/com/d3/notifications/config/NotificationAppConfiguration.kt
- notifications/src/main/kotlin/com/d3/notifications/init/NotificationInitialization.kt
Now Iroha chain listener is split into two: plain Iroha chain listener that listens to block directly from Iroha and reliable chain listener that listens to Rabbit MQ
> Splitting Iroha chain listener

- btc-dw-bridge/src/main/kotlin/com/d3/btc/dwbridge/config/BtcDWBridgeAppConfiguration.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/config/BtcWithdrawalAppConfiguration.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcWithdrawalTestEnvironment.kt
- notary-commons/src/main/kotlin/sidechain/iroha/ReliableIrohaChainListener.kt
By default, RabbitMQ delivery callback will be executed in the thread pool that is created using the 
following code:
`this.executor = (executor == null) ? Executors.newFixedThreadPool(DEFAULT_NUM_THREADS, threadFactory)`
If no executor is specified, fixed thread pool is used. But sometimes it's useful to specify custom consumer thread pool. Especially in `btc-withdrawal-service`, where we assume that every transfer is handled one-by-one in a sequential fashion.
> Configurable Reliable chain listener consumer thread pool

- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcFullPipelineTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcNotaryIntegrationTest.kt
Too many blocks are generated in parallel mode. It causes Bitcoin blockchain corruptions.
> Fixed BTC block generation

- deploy/docker-compose.yml
Add dependency to chain-adapter on RMQ in docker-compose.
> fix chain-adapter depends on rmq

- .gitignore
- btc-dw-bridge/src/main/kotlin/com/d3/btc/dwbridge/config/BtcDWBridgeAppConfiguration.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/config/BtcWithdrawalAppConfiguration.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/init/BtcWithdrawalInitialization.kt
- eth-withdrawal/src/main/kotlin/withdrawalservice/WithdrawalServiceInitialization.kt
- eth/src/main/kotlin/sidechain/eth/EthChainListener.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcFullPipelineTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcMultiAddressGenerationIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcMultiWithdrawalIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcNotaryIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcWithdrawalFailResistanceIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcWithdrawalIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcAddressGenerationTestEnvironment.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcWithdrawalTestEnvironment.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcConfigHelper.kt
- notary-commons/src/main/kotlin/sidechain/ChainListener.kt
- notary-commons/src/main/kotlin/sidechain/iroha/IrohaChainListener.kt
- notary-commons/src/main/kotlin/sidechain/iroha/ReliableIrohaChainListener.kt
Now we can confirm Iroha block delivery safely.
Changes:
1) `subscribe()` in `ReliableIrohaChainListener` must be set BEFORE setting RabbitMQ delivery callback, otherwise blocks may be lost.
2) Every test has its own wallet file.
> Manual BTC withdrawal ack

- deploy/docker-compose-base.yml
- deploy/docker-compose.yml
- docker/chain-adapter.dockerfile
Add wait for d3-rmq and d3-iroha on chain-adapter startup
> add docker-wait-for d3-rmq

- btc-deposit/src/main/kotlin/com/d3/btc/deposit/config/BtcNotaryAppConfiguration.kt
- btc-deposit/src/main/kotlin/com/d3/btc/deposit/handler/BtcDepositTxHandler.kt
- btc-deposit/src/main/kotlin/com/d3/btc/deposit/init/BtcNotaryInitialization.kt
- btc-deposit/src/main/kotlin/com/d3/btc/deposit/listener/BitcoinBlockChainDepositListener.kt
- btc-deposit/src/main/kotlin/com/d3/btc/deposit/listener/BitcoinTransactionListener.kt
- btc-deposit/src/main/kotlin/com/d3/btc/deposit/listener/BtcConfirmedTxListener.kt
- btc-deposit/src/main/kotlin/com/d3/btc/deposit/service/BtcWalletListenerRestartService.kt
- btc-dw-bridge/src/main/kotlin/com/d3/btc/dwbridge/config/BtcDWBridgeAppConfiguration.kt
- btc-dw-bridge/src/main/kotlin/com/d3/btc/dwbridge/main.kt
- btc/src/main/kotlin/com/d3/btc/peer/SharedPeerGroup.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcDepositFailResistanceIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcNotaryTestEnvironment.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcIntegrationHelperUtil.kt
- notary-registration/src/main/kotlin/com/d3/commons/registration/main.kt
This is how deposit service works:
1) Listen to Bitcoin blockchain
2) Add depth listener to transactions that we are interested in (deposits to our clients)
3) Wait for 6 blocks
4)  Publish deposit event
If deposit service fails before transaction hits 6 blocks, we will lose money in Iroha after service restart because there will be no listeners for unconfirmed transactions. We have to manually check if we have unconfirmed transactions and reset depth listeners once again.
> Restart unconfirmed transactions

- btc-address-generation/src/main/kotlin/com/d3/btc/generation/init/BtcAddressGenerationInitialization.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/transaction/SignCollector.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/transaction/TransactionSigner.kt
- btc/src/main/kotlin/com/d3/btc/helper/address/BtcAddressHelper.kt
- btc/src/main/kotlin/com/d3/btc/provider/generation/BtcPublicKeyProvider.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcAddressGenerationIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcMultiAddressGenerationIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcMultiWithdrawalIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcWithdrawalTestEnvironment.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcIntegrationHelperUtil.kt
Bitcoin multisig transaction signatures must be ordered the same way their corresponding public keys were ordered in redeem script. Unfortunately, it was not the case. Now ordering is fixed.
We didn't face this problem before, because all the test were written in 1 node environment, so we couldn't face any ordering issues.
This behavior is guarded by intgeration tests.
> Fixed BTC withdrawal

- btc-address-generation/src/main/kotlin/com/d3/btc/generation/init/BtcAddressGenerationInitialization.kt
- btc-deposit/src/main/kotlin/com/d3/btc/deposit/init/BtcNotaryInitialization.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/init/BtcWithdrawalInitialization.kt
- btc/src/main/kotlin/com/d3/btc/wallet/WalletExt.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcAddressGenerationTestEnvironment.kt
Wrong wallet type may be created accidentally. In order to avoid any problems and money loss, wallet type must be checked before the service start.
> Btc network check

- btc-registration/src/main/kotlin/com/d3/btc/registration/strategy/BtcRegistrationStrategyImpl.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/provider/BtcChangeAddressProvider.kt
- btc/src/main/kotlin/com/d3/btc/model/BtcAddress.kt
- btc/src/main/kotlin/com/d3/btc/provider/account/IrohaBtcAccountRegistrator.kt
- btc/src/main/kotlin/com/d3/btc/provider/generation/BtcPublicKeyProvider.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcRegistrationIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcRegistrationTestEnvironment.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcIntegrationHelperUtil.kt
Now we store generation time inside Bitcoin MultiSig address details. We can use it to block out-of-date addresses. Currently, this value is used to pick the newest address among free to register addresses.
> Storing generation time in Btc address generation

- btc-deposit/README.md
- btc-deposit/src/main/kotlin/com/d3/btc/deposit/config/BtcDepositConfig.kt
- btc-deposit/src/main/kotlin/com/d3/btc/deposit/config/BtcNotaryAppConfiguration.kt
- btc-dw-bridge/src/main/kotlin/com/d3/btc/dwbridge/config/BtcDWBridgeAppConfiguration.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/handler/NewTransferHandler.kt
- btc-withdrawal/src/main/kotlin/com/d3/btc/withdrawal/service/BtcRollbackService.kt
- btc/src/main/kotlin/com/d3/btc/provider/generation/BtcPublicKeyProvider.kt
- configs/btc/deposit_local.properties
- configs/btc/deposit_mainnet.properties
- configs/btc/deposit_testnet.properties
- configs/eth/deposit_local.properties
- configs/eth/deposit_mainnet.properties
- configs/eth/deposit_testnet.properties
- eth/src/main/kotlin/com/d3/eth/deposit/EthDepositConfig.kt
- eth/src/main/kotlin/com/d3/eth/deposit/EthDepositInitialization.kt
- eth/src/test/kotlin/com/d3/commons/notary/NotaryTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcNotaryTestEnvironment.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcWithdrawalTestEnvironment.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcConfigHelper.kt
- notary-commons/src/main/kotlin/com/d3/commons/notary/NotaryImpl.kt
- notary-commons/src/main/kotlin/com/d3/commons/sidechain/iroha/consumer/IrohaConsumer.kt
- notary-commons/src/main/kotlin/com/d3/commons/sidechain/iroha/consumer/IrohaConsumerImpl.kt
- notary-commons/src/main/kotlin/com/d3/commons/sidechain/iroha/util/RequestHelper.kt
- notary-eth-integration-test/src/main/kotlin/integration/helper/EthConfigHelper.kt
Quorum value must be taken from Iroha account, not from `peerListProvider` because it returns the number of peers. Given that fact, `peerListProvider` is not needed in deposit services.
> Fixed quorum

- notary-commons/build.gradle
- notary-commons/src/main/kotlin/com/d3/commons/config/Configs.kt
- notary-commons/src/test/kotlin/com/d3/commons/config/ConfigsPriorityTest.kt
Now we can ignore files and use configs based only on the ENV, but there is an issue we need to include each intermediate node to the variables as well (see in the test). Created an issue https://github.com/jdiazcano/cfg4k/issues/57
> Refactored configs, primary working with ENV

- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcWithdrawalIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcWithdrawalTestEnvironment.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcIntegrationHelperUtil.kt
Redundant transactions were removed from Bitcoin withdrawal test. Now the test works slightly faster.
> Optimizing Bitcoin tests

- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/dto/GenesisBlockModel.kt
- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/genesis/d3/D3TestContext.kt
- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/genesis/d3/D3TestGenesisFactory.kt
- bootstrap/src/test/kotlin/jp/co/soramitsu/bootstrap/IrohaTest.kt
Added nonexistent accounts key checking so that we can enforce key pair generation with proper naming but without actual account creation
> Added nonexistent accounts key checking

- bootstrap/src/integration-test/kotlin/jp/co/soramitsu/bootstrap/ChangelogIntegrationTest.kt
- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/changelog/helper/ChangelogHelper.kt
- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/changelog/mapper/ChangelogMapper.kt
- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/changelog/service/ChangelogExecutor.kt
- bootstrap/src/main/kotlin/jp/co/soramitsu/bootstrap/dto/ChangelogModel.kt
Now the changelog service works in MST fashion. Plus little refactor:
1) Helper functions were moved to the `helper` package
2) Mapping functions were moved to the `mapper` package
3) `ClientKeyPair` is renamed to `AccountKeyPair`
> Mst changelog

- btc-registration/src/main/kotlin/com/d3/btc/registration/config/BtcRegistrationAppConfiguration.kt
- btc-registration/src/main/kotlin/com/d3/btc/registration/init/BtcRegistrationServiceInitialization.kt
- btc-registration/src/main/kotlin/com/d3/btc/registration/strategy/BtcRegistrationStrategyImpl.kt
- btc/src/main/kotlin/com/d3/btc/provider/BtcRegisteredAddressesProvider.kt
- eth-registration/src/main/kotlin/com/d3/eth/registration/EthRegistrationStrategyImpl.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcMultiWithdrawalIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/BtcRegistrationIntegrationTest.kt
- notary-btc-integration-test/src/integration-test/kotlin/integration/btc/environment/BtcRegistrationTestEnvironment.kt
- notary-btc-integration-test/src/main/kotlin/integration/helper/BtcIntegrationHelperUtil.kt
Now we check if we are able to register D3 clients in Bitcoin network. Currently, it just checks if D3 client hasn't been registered previously. This behavior is guarded by the test.
> Forbid double Bitcoin registration

- README.md
No need to store ETH documentation in the notary repository.
> ETH documentation removal

- configs/chain-adapter.properties
- configs/rmq.properties
- notary-commons/src/main/kotlin/com/d3/commons/config/Configs.kt
- notary-commons/src/main/kotlin/com/d3/commons/sidechain/iroha/ReliableIrohaChainListener.kt
Fixed RMQ configuration. The `chain-adapter` service uses `chain-adapter.properties`, while the `ReliableChainListener` uses the same` rmq.properties` file, but now it's thinner.
> Fixed RMQ config

- notary-iroha-integration-test/build.gradle
- notary-iroha-integration-test/src/main/kotlin/integration/helper/ContainerHelper.kt
In order to follow the DRY concept, `ContainerHelper` was moved to the main repository. Feel free to use it.
> Container helper

- notary-commons/src/main/kotlin/com/d3/commons/config/Configs.kt
According to the DevOps team improvements list, we must store key pair data directly in config files. No paths.
> Raw keyPair data

- notary-commons/build.gradle
- notary-commons/src/main/kotlin/com/d3/commons/expansion/ServiceExpansion.kt
- notary-iroha-integration-test/src/integration-test/kotlin/integration/iroha/ServiceExpansionTest.kt
- notary-iroha-integration-test/src/main/kotlin/integration/helper/IrohaAccountHelper.kt
Brand new `ServiceExpansion` class. The class is meant to be used as an Iroha accounts quorum updater.  It listens to Iroha blocks and updates accounts if needed. [Linked pr.](https://github.com/d3ledger/bootstrap-changelog/pull/23)
> Notary expansion service
